GSSubprocess: remove unnecessary NULL check (trivial)
This fixes a warning found during Coverity scan.

  Error: REVERSE_INULL (CWE-476): [#def5]
  libgsystem/gsystem-subprocess.c:949: deref_ptr_in_call: Dereferencing pointer "context".
  libgsystem/gsystem-subprocess-context.c:330:3: deref_parm: Directly dereferencing parameter "self".
  libgsystem/gsystem-subprocess.c:960: check_after_deref: Null-checking "context" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.

Signed-off-by: Thomas Haller <thaller@redhat.com>